// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADw6xK-EgZH0Q3QsV0WGf-lJVHwgCcxEY',
    appId: '1:889574089374:web:9c8264301a93b55c6fd18f',
    messagingSenderId: '889574089374',
    projectId: 'exercise-8-f552f',
    authDomain: 'exercise-8-f552f.firebaseapp.com',
    storageBucket: 'exercise-8-f552f.firebasestorage.app',
    measurementId: 'G-1ECBEYK2X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE5YmlpOJyFWtNIzKtjBsF-LucapTqN-0',
    appId: '1:889574089374:android:c2bace2925f53b096fd18f',
    messagingSenderId: '889574089374',
    projectId: 'exercise-8-f552f',
    storageBucket: 'exercise-8-f552f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzlYHQ5oZOJy4IYbTq04osHMWH56p3tmY',
    appId: '1:889574089374:ios:7cb7c3e194fc7d666fd18f',
    messagingSenderId: '889574089374',
    projectId: 'exercise-8-f552f',
    storageBucket: 'exercise-8-f552f.firebasestorage.app',
    androidClientId: '889574089374-t5elesf8iin51nk6k6q6d5acgdji9qnh.apps.googleusercontent.com',
    iosClientId: '889574089374-lv3kath3o82m7rt96g3n7ge99ochveim.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzlYHQ5oZOJy4IYbTq04osHMWH56p3tmY',
    appId: '1:889574089374:ios:7cb7c3e194fc7d666fd18f',
    messagingSenderId: '889574089374',
    projectId: 'exercise-8-f552f',
    storageBucket: 'exercise-8-f552f.firebasestorage.app',
    androidClientId: '889574089374-t5elesf8iin51nk6k6q6d5acgdji9qnh.apps.googleusercontent.com',
    iosClientId: '889574089374-lv3kath3o82m7rt96g3n7ge99ochveim.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
